# Generated by Django 5.0.3 on 2024-05-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logistics", "0001_initial"),
        ("users", "0002_alter_customer_cus_birth_alter_customer_cus_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question", models.AutoField(primary_key=True, serialize=False)),
                ("question_title", models.CharField(max_length=30)),
                ("question_content", models.TextField()),
                ("question_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("answer", models.AutoField(primary_key=True, serialize=False)),
                ("answer_content", models.TextField()),
                ("answer_date", models.DateTimeField(null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inquiry.question",
                    ),
                ),
            ],
            options={"unique_together": {("question",)},},
        ),
    ]
