# Generated by Django 5.0.4 on 2024-04-24 13:14

import logistics.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=logistics.fields.ThumbnailImageField(upload_to='photo/%Y/%m', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inventory',
            field=models.IntegerField(verbose_name='재고'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sale',
            field=models.IntegerField(default=0, verbose_name='할인율'),
        ),
    ]
