# Generated by Django 5.0.4 on 2024-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
