# Generated by Django 5.0.3 on 2024-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer", name="cus_birth", field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cus_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cus_img",
            field=models.ImageField(blank=True, null=True, upload_to="customer/img"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cus_weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_img",
            field=models.ImageField(blank=True, null=True, upload_to="store/img"),
        ),
    ]
