# Generated by Django 5.0.4 on 2024-06-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('logistics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='community',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.product'),
        ),
        migrations.AddField(
            model_name='community',
            name='community_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.communitycategory'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_comments', to='users.customer'),
        ),
    ]
