# Generated by Django 5.0.4 on 2024-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_posts', to='users.customer'),
        ),
    ]
