# Generated by Django 5.0.4 on 2024-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='selected_products',
            field=models.ManyToManyField(blank=True, related_name='selected_communities', to='logistics.product'),
        ),
    ]
