# Generated by Django 5.0.4 on 2024-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_liked_by'),
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='product',
        ),
        migrations.AddField(
            model_name='community',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='communities', to='logistics.product'),
        ),
    ]
