# Generated by Django 5.0.4 on 2024-06-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_community_product_community_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='products',
            new_name='product',
        ),
    ]
