# Generated by Django 5.0.4 on 2024-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_content", models.TextField(verbose_name="내용")),
                (
                    "answer_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer_Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_title", models.CharField(max_length=30, verbose_name="제목")),
                ("question_content", models.TextField(verbose_name="내용")),
                (
                    "question_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store_Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_title", models.CharField(max_length=30, verbose_name="제목")),
                ("question_content", models.TextField(verbose_name="내용")),
                (
                    "question_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
        ),
    ]
