# Generated by Django 5.0.4 on 2024-06-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("support", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer_question",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="users.customer",
                verbose_name="고객",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="customer_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="support.customer_question",
                verbose_name="질문",
            ),
        ),
        migrations.AddField(
            model_name="store_question",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="users.store",
                verbose_name="상점",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="store_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="support.store_question",
                verbose_name="질문",
            ),
        ),
    ]
